# -*- coding: utf-8 -*-
"""Termodinâmica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wijTOTSMQX2LkZmoZn5lhuoyfaKqagmT
"""

! pip install CoolProp

from CoolProp.CoolProp import PropsSI, PhaseSI

p1 = float(input("Coloque a Pressão do ponto 1 [em KPa]: "))
t1 = float(input("Coloque a Temperatura do Ponto 1 [em Celsius]: "))
p2 = float(input("Coloque a Pressão do ponto 2 [em KPa]: "))

t1si = t1 + 273.15
p1si = p1 * 1000
p2si = p2 * 1000

h1 = PropsSI("H","T",t1si,"P",p1si,"Water")
print("entalpia do ponto 1 {} kj/kg".format(h1/1000))

h2 = h1

t2 = PropsSI("T","H",h1,"P",p2si,"Water")

t2si = int(t2 - 273.15)

print(t2si)

print("A temperatura final do Gás é {}".format(t2si))